# Generated by Django 2.0.4 on 2020-05-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(max_length=50)),
                ('countArray', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exp1',
            },
        ),
        migrations.CreateModel(
            name='exp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(max_length=50)),
                ('countArray', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exp2',
            },
        ),
    ]
